name: code workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              
            - name: List & Read Files
              run: |
                  echo "My Kode GitHub Action job."
                  ls -ltra
                  cat README.md
            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Run for cover... I am DRAGON... awawarr" >> dragon.txt
